language: java
sudo: false
install: true
addons:
  sonarqube: true
env:
  global:
  - secure: 1JOuuLQQ2FHbNwt3ejqxGNSX6MUYwdBTrcWfsN+AZM+OalQIkA06Fc6lhZM+XYdwbOSpZClNjTE3g3Fns+MofxaDMxZIh1qH7yAJ5UpFSzF1XKmtidyqFBK4Qlvb3NTC4oWGeBdjmRShGo75b3uaj0PEVB8HbH74Q6yFOJYn245mfjK5IrcQ3MjlCTvh1lKKA2zO1mPQ56KgdVNDSsVAdJPkyRNmAm5NY8AbvBeyagOKxob/dbX8PEbV/faOEe5Pi3P/nivY/h9ZC0ZoqzoK1k2Osu/8cjxzzJ7g+AC2RGLiwTBn2/dCSukZmZGvodTIKhvcOaK09BWuJPqDLu7yAgOubG6gCJY/mLPT7dinp/sBXO0/Ej6HUH1lJ2+pt17o0eL/dWKO0Q6n0JRNz0N1jDR4fhlimQbnnP3VGjj2SkodmMeI7xyWt8BJwIIqkPxdxIKB87rg9Hfl/OB2K9MGReHS7ak2CweoGZqVxmX9+qahtVnouq46xvzKwU0SOCrXBs9tsnNUyDsgUHe4y8j/PClHRKzCi8ZtWHey6bQsN2RlSkkInzDS310KEBKvf4IF8vN7Vi4qE4Pq4JwdKDxO5mRXvq6uNaYfGAm38qMg1+R69gnwpJU5q523aolvJT6S5sMK1dBTAzuoGAeJl+LUfNdbSCF45LsgLprUUDMJ2Ms=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email:
  - jep0042@gmail.com
